version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ai_review_postgres
    restart: always
    environment:
      POSTGRES_DB: aidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: